//Copyright (c) 2004-2020 Microchip Technology Inc. and its subsidiaries.
//SPDX-License-Identifier: MIT



#include "common.h"     /* Always include common.h at the first place of user-defined herder files */
#include "sysutil.h"
#include "event.h"

#include "interrupt.h"
#include "hwport.h"
#include "spiflash.h"
#include "timer.h"
#include "uartdrv.h"
#include "phytsk.h"
#include "print.h"
#include "clihnd.h"
#include "phydrv.h"
#include "phymap.h"
#include "phy_family.h"
#include "phy_base.h"
#include "h2.h"
#include "h2txrx.h"

#include "misc2.h"
#include "i2c_h.h"
#if UNMANAGED_PORT_STATISTICS_IF
#include "h2stats.h"
#endif

#include "taskdef.h"

#if TRANSIT_FAN_CONTROL
#include "fan_api.h"
#endif

#if TRANSIT_SNMP
#include "snmp.h"
#include "traps.h"
#endif /* TRANSIT_SNMP */

#if TRANSIT_LLDP
#include "lldp.h"
#endif /* TRANSIT_LLDP */

#if TRANSIT_EEE
#include "eee_api.h"
#include "eee_base_api.h"
#endif

#if TRANSIT_LOOPDETECT
#include "loopdet.h"
#endif

#if TRANSIT_POE
#include "poetsk.h"
#endif /* TRANSIT_POE */

#if TRANSIT_POE_LLDP
#include "poe_os.h"
#endif

#if FRONT_LED_PRESENT
#include "ledtsk.h"
#endif

#include "main.h"
#include "stdio.h"


#include "vtss_ocelot_regs_devcpu_gcb.h"
#include "vtss_ocelot_regs_icpu_cfg.h"
#include "vtss_ocelot_regs_uart.h"
#include "vtss_ocelot_regs_hsio.h"
#include "h2io.h"
vtss_rc vtss_ferret_sd6g_ib_cal(void)
{
  vtss_rc status = VTSS_RC_OK;
  vtss_rc status2 = VTSS_RC_OK;
  u32     value;
  u32     addr = 0x7; /* Calibrate IB of all 3 SD6G macros */

  /* 1. Detune LCPLL */
  CSR_WR(VTSS_HSIO_PLL5G_CFG_PLL5G_CFG2,
         VTSS_F_HSIO_PLL5G_CFG_PLL5G_CFG2_ENA_GAIN_TEST(1) |
         VTSS_F_HSIO_PLL5G_CFG_PLL5G_CFG2_GAIN_TEST(0),
         VTSS_M_HSIO_PLL5G_CFG_PLL5G_CFG2_ENA_GAIN_TEST |
         VTSS_M_HSIO_PLL5G_CFG_PLL5G_CFG2_GAIN_TEST);

  /* 2. Prepare and execute IB-Calibration */
  CSR_WR(VTSS_HSIO_SERDES6G_ANA_CFG_SERDES6G_PLL_CFG,
         VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_PLL_CFG_PLL_FSM_ENA(0),
         VTSS_M_HSIO_SERDES6G_ANA_CFG_SERDES6G_PLL_CFG_PLL_FSM_ENA);

  CSR_WR(VTSS_HSIO_SERDES6G_ANA_CFG_SERDES6G_COMMON_CFG,
         VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_COMMON_CFG_SYS_RST(0),
         VTSS_M_HSIO_SERDES6G_ANA_CFG_SERDES6G_COMMON_CFG_SYS_RST);

  CSR_WR(VTSS_HSIO_SERDES6G_DIG_CFG_SERDES6G_MISC_CFG,
         VTSS_F_HSIO_SERDES6G_DIG_CFG_SERDES6G_MISC_CFG_LANE_RST(1),
         VTSS_M_HSIO_SERDES6G_DIG_CFG_SERDES6G_MISC_CFG_LANE_RST);

  vtss_sd6g65_mcb_transfer (addr);

  CSR_WR(VTSS_HSIO_SERDES6G_ANA_CFG_SERDES6G_COMMON_CFG,
         VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_COMMON_CFG_PWD_TX(0) |
         VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_COMMON_CFG_PWD_RX(0) |
         VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_COMMON_CFG_ENA_LANE(1) |
         VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_COMMON_CFG_SYS_RST(1),
         VTSS_M_HSIO_SERDES6G_ANA_CFG_SERDES6G_COMMON_CFG_PWD_TX |
         VTSS_M_HSIO_SERDES6G_ANA_CFG_SERDES6G_COMMON_CFG_PWD_RX |
         VTSS_M_HSIO_SERDES6G_ANA_CFG_SERDES6G_COMMON_CFG_ENA_LANE |
         VTSS_M_HSIO_SERDES6G_ANA_CFG_SERDES6G_COMMON_CFG_SYS_RST);

  CSR_WR(VTSS_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG,
         VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG_IB_RTRM_ADJ(13),
         VTSS_M_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG_IB_RTRM_ADJ);

  CSR_WR(VTSS_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG,
         VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG_IB_CONCUR(1) |
         VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG_IB_SAM_ENA(1) |
         VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG_IB_EQZ_ENA(1) |
         VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG_IB_REG_ENA(1) |
         VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG_IB_SIG_DET_ENA(1),
         VTSS_M_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG_IB_CONCUR |
         VTSS_M_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG_IB_SAM_ENA |
         VTSS_M_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG_IB_EQZ_ENA |
         VTSS_M_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG_IB_REG_ENA |
         VTSS_M_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG_IB_SIG_DET_ENA);

  CSR_WR(VTSS_HSIO_SERDES6G_ANA_CFG_SERDES6G_PLL_CFG,
         VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_PLL_CFG_PLL_DIV4(0) |
         VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_PLL_CFG_PLL_ENA_ROT(0),
         VTSS_M_HSIO_SERDES6G_ANA_CFG_SERDES6G_PLL_CFG_PLL_DIV4 |
         VTSS_M_HSIO_SERDES6G_ANA_CFG_SERDES6G_PLL_CFG_PLL_ENA_ROT);

  CSR_WR(VTSS_HSIO_SERDES6G_ANA_CFG_SERDES6G_PLL_CFG,
         VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_PLL_CFG_PLL_ROT_DIR(0) |
         VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_PLL_CFG_PLL_ROT_FRQ(0) |
         VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_PLL_CFG_PLL_FSM_CTRL_DATA(60),
         VTSS_M_HSIO_SERDES6G_ANA_CFG_SERDES6G_PLL_CFG_PLL_ROT_DIR |
         VTSS_M_HSIO_SERDES6G_ANA_CFG_SERDES6G_PLL_CFG_PLL_ROT_FRQ |
         VTSS_M_HSIO_SERDES6G_ANA_CFG_SERDES6G_PLL_CFG_PLL_FSM_CTRL_DATA);

  CSR_WR(VTSS_HSIO_SERDES6G_ANA_CFG_SERDES6G_COMMON_CFG,
         VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_COMMON_CFG_IF_MODE(1) |
         VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_COMMON_CFG_HRATE(0) |
         VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_COMMON_CFG_QRATE(1),
         VTSS_M_HSIO_SERDES6G_ANA_CFG_SERDES6G_COMMON_CFG_IF_MODE |
         VTSS_M_HSIO_SERDES6G_ANA_CFG_SERDES6G_COMMON_CFG_HRATE |
         VTSS_M_HSIO_SERDES6G_ANA_CFG_SERDES6G_COMMON_CFG_QRATE);

  vtss_sd6g65_mcb_transfer (addr);

  CSR_WR(VTSS_HSIO_SERDES6G_ANA_CFG_SERDES6G_PLL_CFG,
         VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_PLL_CFG_PLL_FSM_ENA(1),
         VTSS_M_HSIO_SERDES6G_ANA_CFG_SERDES6G_PLL_CFG_PLL_FSM_ENA);

  vtss_sd6g65_mcb_transfer (addr);

  VTSS_MSLEEP(2);

  vtss_sd6g65_mcb_readback (addr);

  CSR_RD(VTSS_HSIO_SERDES6G_ANA_STATUS_SERDES6G_PLL_STATUS, &value);
  if (VTSS_X_HSIO_SERDES6G_ANA_STATUS_SERDES6G_PLL_STATUS_PLL_CAL_NOT_DONE(value) != 0) {
    VTSS_E("HSIO::SERDES6G_PLL_STATUS.PLL_CAL_NOT_DONE is not 0!");
    status = VTSS_RC_ERROR;
  };

  CSR_RD(VTSS_HSIO_SERDES6G_ANA_STATUS_SERDES6G_PLL_STATUS, &value);
  if (VTSS_X_HSIO_SERDES6G_ANA_STATUS_SERDES6G_PLL_STATUS_PLL_OUT_OF_RANGE_ERR(value) != 0) {
    VTSS_E("HSIO::SERDES6G_PLL_STATUS.PLL_OUT_OF_RANGE_ERR is not 0!");
    status = VTSS_RC_ERROR;
  };

  CSR_RD(VTSS_HSIO_SERDES6G_ANA_STATUS_SERDES6G_PLL_STATUS, &value);
  if (VTSS_X_HSIO_SERDES6G_ANA_STATUS_SERDES6G_PLL_STATUS_PLL_CAL_ERR(value) != 0) {
    VTSS_E("HSIO::SERDES6G_PLL_STATUS.PLL_CAL_ERR is not 0!");
    status = VTSS_RC_ERROR;
  };

  CSR_WR(VTSS_HSIO_SERDES6G_DIG_CFG_SERDES6G_MISC_CFG,
         VTSS_F_HSIO_SERDES6G_DIG_CFG_SERDES6G_MISC_CFG_LANE_RST(0),
         VTSS_M_HSIO_SERDES6G_DIG_CFG_SERDES6G_MISC_CFG_LANE_RST);

  CSR_WR(VTSS_HSIO_SERDES6G_ANA_CFG_SERDES6G_COMMON_CFG,
         VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_COMMON_CFG_PWD_TX(1),
         VTSS_M_HSIO_SERDES6G_ANA_CFG_SERDES6G_COMMON_CFG_PWD_TX);

  vtss_sd6g65_mcb_transfer (addr);

  CSR_WR(VTSS_HSIO_SERDES6G_DIG_CFG_SERDES6G_DFT_CFG2,
         VTSS_F_HSIO_SERDES6G_DIG_CFG_SERDES6G_DFT_CFG2_RX_STEP_FREQ(2) |
         VTSS_F_HSIO_SERDES6G_DIG_CFG_SERDES6G_DFT_CFG2_RX_JI_ENA(0) |
         VTSS_F_HSIO_SERDES6G_DIG_CFG_SERDES6G_DFT_CFG2_RX_FREQOFF_DIR(0) |
         VTSS_F_HSIO_SERDES6G_DIG_CFG_SERDES6G_DFT_CFG2_RX_FREQOFF_ENA(1),
         VTSS_M_HSIO_SERDES6G_DIG_CFG_SERDES6G_DFT_CFG2_RX_STEP_FREQ |
         VTSS_M_HSIO_SERDES6G_DIG_CFG_SERDES6G_DFT_CFG2_RX_JI_ENA |
         VTSS_M_HSIO_SERDES6G_DIG_CFG_SERDES6G_DFT_CFG2_RX_FREQOFF_DIR |
         VTSS_M_HSIO_SERDES6G_DIG_CFG_SERDES6G_DFT_CFG2_RX_FREQOFF_ENA);

  CSR_WR(VTSS_HSIO_SERDES6G_DIG_CFG_SERDES6G_DFT_CFG0,
         VTSS_F_HSIO_SERDES6G_DIG_CFG_SERDES6G_DFT_CFG0_RX_DFT_ENA(1),
         VTSS_M_HSIO_SERDES6G_DIG_CFG_SERDES6G_DFT_CFG0_RX_DFT_ENA);

  CSR_WR(VTSS_HSIO_SERDES6G_ANA_CFG_SERDES6G_DES_CFG,
         VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_DES_CFG_DES_CPMD_SEL(2),
         VTSS_M_HSIO_SERDES6G_ANA_CFG_SERDES6G_DES_CFG_DES_CPMD_SEL);

  vtss_sd6g65_mcb_transfer (addr);

  CSR_WR(VTSS_HSIO_SERDES6G_ANA_CFG_SERDES6G_COMMON_CFG,
         VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_COMMON_CFG_ENA_ELOOP(0),
         VTSS_M_HSIO_SERDES6G_ANA_CFG_SERDES6G_COMMON_CFG_ENA_ELOOP);

  CSR_WR(VTSS_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG,
         VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG_IB_SIG_DET_CLK_SEL(0),
         VTSS_M_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG_IB_SIG_DET_CLK_SEL);

  CSR_WR(VTSS_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG,
         VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG_IB_CAL_ENA(0) |
         VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG_IB_REG_PAT_SEL_OFFSET(0),
         VTSS_M_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG_IB_CAL_ENA |
         VTSS_M_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG_IB_REG_PAT_SEL_OFFSET);

  CSR_WR(VTSS_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG1,
         VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG1_IB_TSDET(16) |
         VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG1_IB_SCALY(15),
         VTSS_M_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG1_IB_TSDET |
         VTSS_M_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG1_IB_SCALY);


  do {

    status2 = VTSS_RC_OK;

    CSR_WR(VTSS_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG,
           VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG_IB_CAL_ENA(0),
           VTSS_M_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG_IB_CAL_ENA);

    CSR_WR(VTSS_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG1,
           VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG1_IB_FILT_OFFSET(0) |
           VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG1_IB_FRC_OFFSET(1),
           VTSS_M_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG1_IB_FILT_OFFSET |
           VTSS_M_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG1_IB_FRC_OFFSET);

    vtss_sd6g65_mcb_transfer (addr);

    CSR_WR(VTSS_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG,
           VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG_IB_CAL_ENA(1),
           VTSS_M_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG_IB_CAL_ENA);

    vtss_sd6g65_mcb_transfer (addr);

    CSR_WR(VTSS_HSIO_SERDES6G_ANA_CFG_SERDES6G_GP_CFG,
           VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_GP_CFG_GP_LSB(768),
           VTSS_M_HSIO_SERDES6G_ANA_CFG_SERDES6G_GP_CFG_GP_LSB);

    vtss_sd6g65_mcb_transfer (addr);

    CSR_WR(VTSS_HSIO_SERDES6G_ANA_CFG_SERDES6G_GP_CFG,
           VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_GP_CFG_GP_LSB(769),
           VTSS_M_HSIO_SERDES6G_ANA_CFG_SERDES6G_GP_CFG_GP_LSB);

    vtss_sd6g65_mcb_transfer (addr);

    CSR_WR(VTSS_HSIO_SERDES6G_ANA_CFG_SERDES6G_GP_CFG,
           VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_GP_CFG_GP_LSB(768),
           VTSS_M_HSIO_SERDES6G_ANA_CFG_SERDES6G_GP_CFG_GP_LSB);

    vtss_sd6g65_mcb_transfer (addr);

    CSR_WR(VTSS_HSIO_SERDES6G_ANA_CFG_SERDES6G_GP_CFG,
           VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_GP_CFG_GP_LSB(769),
           VTSS_M_HSIO_SERDES6G_ANA_CFG_SERDES6G_GP_CFG_GP_LSB);

    vtss_sd6g65_mcb_transfer (addr);

    CSR_WR(VTSS_HSIO_SERDES6G_ANA_CFG_SERDES6G_GP_CFG,
           VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_GP_CFG_GP_LSB(768),
           VTSS_M_HSIO_SERDES6G_ANA_CFG_SERDES6G_GP_CFG_GP_LSB);

    vtss_sd6g65_mcb_transfer (addr);

    CSR_WR(VTSS_HSIO_SERDES6G_ANA_CFG_SERDES6G_GP_CFG,
           VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_GP_CFG_GP_LSB(769),
           VTSS_M_HSIO_SERDES6G_ANA_CFG_SERDES6G_GP_CFG_GP_LSB);

    vtss_sd6g65_mcb_transfer (addr);

    CSR_WR(VTSS_HSIO_SERDES6G_ANA_CFG_SERDES6G_GP_CFG,
           VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_GP_CFG_GP_LSB(768),
           VTSS_M_HSIO_SERDES6G_ANA_CFG_SERDES6G_GP_CFG_GP_LSB);

    vtss_sd6g65_mcb_transfer (addr);

    CSR_WR(VTSS_HSIO_SERDES6G_ANA_CFG_SERDES6G_GP_CFG,
           VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_GP_CFG_GP_LSB(769),
           VTSS_M_HSIO_SERDES6G_ANA_CFG_SERDES6G_GP_CFG_GP_LSB);

    vtss_sd6g65_mcb_transfer (addr);

    CSR_WR(VTSS_HSIO_SERDES6G_ANA_CFG_SERDES6G_GP_CFG,
           VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_GP_CFG_GP_LSB(768),
           VTSS_M_HSIO_SERDES6G_ANA_CFG_SERDES6G_GP_CFG_GP_LSB);

    vtss_sd6g65_mcb_transfer (addr);

    CSR_WR(VTSS_HSIO_SERDES6G_ANA_CFG_SERDES6G_GP_CFG,
           VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_GP_CFG_GP_LSB(769),
           VTSS_M_HSIO_SERDES6G_ANA_CFG_SERDES6G_GP_CFG_GP_LSB);

    vtss_sd6g65_mcb_transfer (addr);

    CSR_WR(VTSS_HSIO_SERDES6G_ANA_CFG_SERDES6G_GP_CFG,
           VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_GP_CFG_GP_LSB(768),
           VTSS_M_HSIO_SERDES6G_ANA_CFG_SERDES6G_GP_CFG_GP_LSB);

    CSR_WR(VTSS_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG1,
           VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG1_IB_FILT_OFFSET(1),
           VTSS_M_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG1_IB_FILT_OFFSET);

    vtss_sd6g65_mcb_transfer (addr);

    vtss_sd6g65_mcb_readback (addr);

    CSR_RD(VTSS_HSIO_SERDES6G_ANA_STATUS_SERDES6G_IB_STATUS0, &value);
    if (VTSS_X_HSIO_SERDES6G_ANA_STATUS_SERDES6G_IB_STATUS0_IB_CAL_DONE(value) != 0) {
      VTSS_E("HSIO::SERDES6G_IB_STATUS0.IB_CAL_DONE is not 0!");
      status2 = VTSS_RC_ERROR;
    };

    CSR_WR(VTSS_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG1,
           VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG1_IB_FRC_OFFSET(0),
           VTSS_M_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG1_IB_FRC_OFFSET);

    vtss_sd6g65_mcb_transfer (addr);

    VTSS_MSLEEP(200);

    /* 3. Check successful IB-Calibration per lane */
    vtss_sd6g65_mcb_readback(1);

    CSR_RD(VTSS_HSIO_SERDES6G_ANA_STATUS_SERDES6G_IB_STATUS0, &value);
    if (VTSS_X_HSIO_SERDES6G_ANA_STATUS_SERDES6G_IB_STATUS0_IB_CAL_DONE(value) != 1) {
      VTSS_E("HSIO::SERDES6G_IB_STATUS0.IB_CAL_DONE is not 1!");
      status2 = VTSS_RC_ERROR;
    };

    vtss_sd6g65_mcb_readback(2);

    CSR_RD(VTSS_HSIO_SERDES6G_ANA_STATUS_SERDES6G_IB_STATUS0, &value);
    if (VTSS_X_HSIO_SERDES6G_ANA_STATUS_SERDES6G_IB_STATUS0_IB_CAL_DONE(value) != 1) {
      VTSS_E("HSIO::SERDES6G_IB_STATUS0.IB_CAL_DONE is not 1!");
      status2 = VTSS_RC_ERROR;
    };

    vtss_sd6g65_mcb_readback(4);

    CSR_RD(VTSS_HSIO_SERDES6G_ANA_STATUS_SERDES6G_IB_STATUS0, &value);
    if (VTSS_X_HSIO_SERDES6G_ANA_STATUS_SERDES6G_IB_STATUS0_IB_CAL_DONE(value) != 1) {
      VTSS_E("HSIO::SERDES6G_IB_STATUS0.IB_CAL_DONE is not 1!");
      status2 = VTSS_RC_ERROR;
    };

  } while (status2 != VTSS_RC_OK);


  /* Disable FoJi and power-down macro */
  CSR_WR(VTSS_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG,
         VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG_IB_SIG_DET_CLK_SEL(7),
         VTSS_M_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG_IB_SIG_DET_CLK_SEL);

  CSR_WR(VTSS_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG1,
         VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG1_IB_TSDET(3),
         VTSS_M_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG1_IB_TSDET);

  CSR_WR(VTSS_HSIO_SERDES6G_ANA_CFG_SERDES6G_DES_CFG,
         VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_DES_CFG_DES_CPMD_SEL(0),
         VTSS_M_HSIO_SERDES6G_ANA_CFG_SERDES6G_DES_CFG_DES_CPMD_SEL);

  CSR_WR(VTSS_HSIO_SERDES6G_DIG_CFG_SERDES6G_DFT_CFG0,
         VTSS_F_HSIO_SERDES6G_DIG_CFG_SERDES6G_DFT_CFG0_RX_DFT_ENA(0),
         VTSS_M_HSIO_SERDES6G_DIG_CFG_SERDES6G_DFT_CFG0_RX_DFT_ENA);

  CSR_WR(VTSS_HSIO_SERDES6G_DIG_CFG_SERDES6G_DFT_CFG2,
         VTSS_F_HSIO_SERDES6G_DIG_CFG_SERDES6G_DFT_CFG2_RX_JI_ENA(0) |
         VTSS_F_HSIO_SERDES6G_DIG_CFG_SERDES6G_DFT_CFG2_RX_FREQOFF_ENA(0),
         VTSS_M_HSIO_SERDES6G_DIG_CFG_SERDES6G_DFT_CFG2_RX_JI_ENA |
         VTSS_M_HSIO_SERDES6G_DIG_CFG_SERDES6G_DFT_CFG2_RX_FREQOFF_ENA);

  CSR_WR(VTSS_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG,
         VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG_IB_CONCUR(0) |
         VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG_IB_EQZ_ENA(0) |
         VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG_IB_SAM_ENA(0) |
         VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG_IB_REG_ENA(0) |
         VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG_IB_SIG_DET_ENA(0),
         VTSS_M_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG_IB_CONCUR |
         VTSS_M_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG_IB_EQZ_ENA |
         VTSS_M_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG_IB_SAM_ENA |
         VTSS_M_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG_IB_REG_ENA |
         VTSS_M_HSIO_SERDES6G_ANA_CFG_SERDES6G_IB_CFG_IB_SIG_DET_ENA);

  CSR_WR(VTSS_HSIO_SERDES6G_ANA_CFG_SERDES6G_COMMON_CFG,
         VTSS_F_HSIO_SERDES6G_ANA_CFG_SERDES6G_COMMON_CFG_ENA_LANE(0),
         VTSS_M_HSIO_SERDES6G_ANA_CFG_SERDES6G_COMMON_CFG_ENA_LANE);

  vtss_sd6g65_mcb_transfer (addr);




  /* 4. Tune LCPLL again */
  CSR_WR(VTSS_HSIO_PLL5G_CFG_PLL5G_CFG2,
         VTSS_F_HSIO_PLL5G_CFG_PLL5G_CFG2_ENA_GAIN_TEST(0),
         VTSS_M_HSIO_PLL5G_CFG_PLL5G_CFG2_ENA_GAIN_TEST);

  /* 5. Wait until LCPLL stable again */
  VTSS_MSLEEP(2);

  return status;
}

