//Copyright (c) 2004-2020 Microchip Technology Inc. and its subsidiaries.
//SPDX-License-Identifier: MIT



#include "common.h"     /* Always include common.h at the first place of user-defined herder files */
#include "sysutil.h"
#include "event.h"

#include "interrupt.h"
#include "hwport.h"
#include "spiflash.h"
#include "timer.h"
#include "uartdrv.h"
#include "phytsk.h"
#include "print.h"
#include "clihnd.h"
#include "phydrv.h"
#include "phymap.h"
#include "phy_family.h"
#include "phy_base.h"
#include "h2.h"
#include "h2txrx.h"

#include "misc2.h"
#include "i2c_h.h"
#if UNMANAGED_PORT_STATISTICS_IF
#include "h2stats.h"
#endif

#include "taskdef.h"

#if TRANSIT_FAN_CONTROL
#include "fan_api.h"
#endif

#if TRANSIT_SNMP
#include "snmp.h"
#include "traps.h"
#endif /* TRANSIT_SNMP */

#if TRANSIT_LLDP
#include "lldp.h"
#endif /* TRANSIT_LLDP */

#if TRANSIT_EEE
#include "eee_api.h"
#include "eee_base_api.h"
#endif

#if TRANSIT_LOOPDETECT
#include "loopdet.h"
#endif

#if TRANSIT_POE
#include "poetsk.h"
#endif /* TRANSIT_POE */

#if TRANSIT_POE_LLDP
#include "poe_os.h"
#endif

#if FRONT_LED_PRESENT
#include "ledtsk.h"
#endif

#include "main.h"
#include "stdio.h"


#include "vtss_ocelot_regs_devcpu_gcb.h"
#include "vtss_ocelot_regs_icpu_cfg.h"
#include "vtss_ocelot_regs_uart.h"
#include "vtss_ocelot_regs_hsio.h"
#include "h2io.h"
void vtss_sd1g65_mcb_transfer (u32 addr) {

  u32 value;

  CSR_WR(VTSS_HSIO_MCB_SERDES1G_CFG_MCB_SERDES1G_ADDR_CFG,
         VTSS_F_HSIO_MCB_SERDES1G_CFG_MCB_SERDES1G_ADDR_CFG_SERDES1G_ADDR(addr) |
         VTSS_F_HSIO_MCB_SERDES1G_CFG_MCB_SERDES1G_ADDR_CFG_SERDES1G_WR_ONE_SHOT(1),
         VTSS_M_HSIO_MCB_SERDES1G_CFG_MCB_SERDES1G_ADDR_CFG_SERDES1G_ADDR |
         VTSS_M_HSIO_MCB_SERDES1G_CFG_MCB_SERDES1G_ADDR_CFG_SERDES1G_WR_ONE_SHOT);

  do {
    CSR_RD(VTSS_HSIO_MCB_SERDES1G_CFG_MCB_SERDES1G_ADDR_CFG, &value);
  } while (VTSS_X_HSIO_MCB_SERDES1G_CFG_MCB_SERDES1G_ADDR_CFG_SERDES1G_WR_ONE_SHOT(value) == 1);
}

void vtss_sd1g65_mcb_readback (u32 addr) {

  u32 value;

  CSR_WR(VTSS_HSIO_MCB_SERDES1G_CFG_MCB_SERDES1G_ADDR_CFG,
         VTSS_F_HSIO_MCB_SERDES1G_CFG_MCB_SERDES1G_ADDR_CFG_SERDES1G_ADDR(addr) |
         VTSS_F_HSIO_MCB_SERDES1G_CFG_MCB_SERDES1G_ADDR_CFG_SERDES1G_RD_ONE_SHOT(1),
         VTSS_M_HSIO_MCB_SERDES1G_CFG_MCB_SERDES1G_ADDR_CFG_SERDES1G_ADDR |
         VTSS_M_HSIO_MCB_SERDES1G_CFG_MCB_SERDES1G_ADDR_CFG_SERDES1G_RD_ONE_SHOT);

  do {
    CSR_RD(VTSS_HSIO_MCB_SERDES1G_CFG_MCB_SERDES1G_ADDR_CFG, &value);
  } while (VTSS_X_HSIO_MCB_SERDES1G_CFG_MCB_SERDES1G_ADDR_CFG_SERDES1G_RD_ONE_SHOT(value) == 1);
}

vtss_rc vtss_ferret_sd1g_cfg_sgmii(u32 addr)
{
  vtss_rc status = VTSS_RC_OK;
  u32     value;

  CSR_WR(VTSS_HSIO_SERDES1G_ANA_CFG_SERDES1G_PLL_CFG,
         VTSS_F_HSIO_SERDES1G_ANA_CFG_SERDES1G_PLL_CFG_PLL_FSM_ENA(0),
         VTSS_M_HSIO_SERDES1G_ANA_CFG_SERDES1G_PLL_CFG_PLL_FSM_ENA);

  CSR_WR(VTSS_HSIO_SERDES1G_ANA_CFG_SERDES1G_COMMON_CFG,
         VTSS_F_HSIO_SERDES1G_ANA_CFG_SERDES1G_COMMON_CFG_SYS_RST(0),
         VTSS_M_HSIO_SERDES1G_ANA_CFG_SERDES1G_COMMON_CFG_SYS_RST);

  vtss_sd1g65_mcb_transfer (addr);

  CSR_WR(VTSS_HSIO_SERDES1G_ANA_CFG_SERDES1G_OB_CFG,
         VTSS_F_HSIO_SERDES1G_ANA_CFG_SERDES1G_OB_CFG_OB_AMP_CTRL(12),
         VTSS_M_HSIO_SERDES1G_ANA_CFG_SERDES1G_OB_CFG_OB_AMP_CTRL);

  CSR_WR(VTSS_HSIO_SERDES1G_DIG_CFG_SERDES1G_MISC_CFG,
         VTSS_F_HSIO_SERDES1G_DIG_CFG_SERDES1G_MISC_CFG_DES_100FX_CPMD_ENA(0) |
         VTSS_F_HSIO_SERDES1G_DIG_CFG_SERDES1G_MISC_CFG_DES_100FX_CPMD_MODE(1) |
         VTSS_F_HSIO_SERDES1G_DIG_CFG_SERDES1G_MISC_CFG_LANE_RST(1),
         VTSS_M_HSIO_SERDES1G_DIG_CFG_SERDES1G_MISC_CFG_DES_100FX_CPMD_ENA |
         VTSS_M_HSIO_SERDES1G_DIG_CFG_SERDES1G_MISC_CFG_DES_100FX_CPMD_MODE |
         VTSS_M_HSIO_SERDES1G_DIG_CFG_SERDES1G_MISC_CFG_LANE_RST);

  CSR_WR(VTSS_HSIO_SERDES1G_ANA_CFG_SERDES1G_PLL_CFG,
         VTSS_F_HSIO_SERDES1G_ANA_CFG_SERDES1G_PLL_CFG_PLL_FSM_ENA(1),
         VTSS_M_HSIO_SERDES1G_ANA_CFG_SERDES1G_PLL_CFG_PLL_FSM_ENA);

  CSR_WR(VTSS_HSIO_SERDES1G_ANA_CFG_SERDES1G_COMMON_CFG,
         VTSS_F_HSIO_SERDES1G_ANA_CFG_SERDES1G_COMMON_CFG_ENA_LANE(1),
         VTSS_M_HSIO_SERDES1G_ANA_CFG_SERDES1G_COMMON_CFG_ENA_LANE);

  CSR_WR(VTSS_HSIO_SERDES1G_ANA_CFG_SERDES1G_IB_CFG,
         VTSS_F_HSIO_SERDES1G_ANA_CFG_SERDES1G_IB_CFG_IB_FX100_ENA(0),
         VTSS_M_HSIO_SERDES1G_ANA_CFG_SERDES1G_IB_CFG_IB_FX100_ENA);

  CSR_WR(VTSS_HSIO_SERDES1G_ANA_CFG_SERDES1G_DES_CFG,
         VTSS_F_HSIO_SERDES1G_ANA_CFG_SERDES1G_DES_CFG_DES_CPMD_SEL(0),
         VTSS_M_HSIO_SERDES1G_ANA_CFG_SERDES1G_DES_CFG_DES_CPMD_SEL);

  vtss_sd1g65_mcb_transfer (addr);

  CSR_WR(VTSS_HSIO_SERDES1G_ANA_CFG_SERDES1G_COMMON_CFG,
         VTSS_F_HSIO_SERDES1G_ANA_CFG_SERDES1G_COMMON_CFG_SYS_RST(1),
         VTSS_M_HSIO_SERDES1G_ANA_CFG_SERDES1G_COMMON_CFG_SYS_RST);

  vtss_sd1g65_mcb_transfer (addr);

  VTSS_MSLEEP(2);

  vtss_sd1g65_mcb_readback (addr);

  CSR_RD(VTSS_HSIO_SERDES1G_ANA_STATUS_SERDES1G_PLL_STATUS, &value);
  if (VTSS_X_HSIO_SERDES1G_ANA_STATUS_SERDES1G_PLL_STATUS_PLL_CAL_NOT_DONE(value) != 0) {
    VTSS_E("HSIO::SERDES1G_PLL_STATUS.PLL_CAL_NOT_DONE is not 0!");
    status = VTSS_RC_ERROR;
  };

  CSR_RD(VTSS_HSIO_SERDES1G_ANA_STATUS_SERDES1G_PLL_STATUS, &value);
  if (VTSS_X_HSIO_SERDES1G_ANA_STATUS_SERDES1G_PLL_STATUS_PLL_OUT_OF_RANGE_ERR(value) != 0) {
    VTSS_E("HSIO::SERDES1G_PLL_STATUS.PLL_OUT_OF_RANGE_ERR is not 0!");
    status = VTSS_RC_ERROR;
  };

  CSR_RD(VTSS_HSIO_SERDES1G_ANA_STATUS_SERDES1G_PLL_STATUS, &value);
  if (VTSS_X_HSIO_SERDES1G_ANA_STATUS_SERDES1G_PLL_STATUS_PLL_CAL_ERR(value) != 0) {
    VTSS_E("HSIO::SERDES1G_PLL_STATUS.PLL_CAL_ERR is not 0!");
    status = VTSS_RC_ERROR;
  };

  CSR_WR(VTSS_HSIO_SERDES1G_DIG_CFG_SERDES1G_MISC_CFG,
         VTSS_F_HSIO_SERDES1G_DIG_CFG_SERDES1G_MISC_CFG_LANE_RST(0),
         VTSS_M_HSIO_SERDES1G_DIG_CFG_SERDES1G_MISC_CFG_LANE_RST);

  CSR_WR(VTSS_HSIO_SERDES1G_ANA_CFG_SERDES1G_COMMON_CFG,
         VTSS_F_HSIO_SERDES1G_ANA_CFG_SERDES1G_COMMON_CFG_ENA_ILOOP(0) |
         VTSS_F_HSIO_SERDES1G_ANA_CFG_SERDES1G_COMMON_CFG_ENA_FLOOP(0) |
         VTSS_F_HSIO_SERDES1G_ANA_CFG_SERDES1G_COMMON_CFG_ENA_ELOOP(0),
         VTSS_M_HSIO_SERDES1G_ANA_CFG_SERDES1G_COMMON_CFG_ENA_ILOOP |
         VTSS_M_HSIO_SERDES1G_ANA_CFG_SERDES1G_COMMON_CFG_ENA_FLOOP |
         VTSS_M_HSIO_SERDES1G_ANA_CFG_SERDES1G_COMMON_CFG_ENA_ELOOP);

  CSR_WR(VTSS_HSIO_SERDES1G_ANA_CFG_SERDES1G_SER_CFG,
         VTSS_F_HSIO_SERDES1G_ANA_CFG_SERDES1G_SER_CFG_SER_EN_WIN(0) |
         VTSS_F_HSIO_SERDES1G_ANA_CFG_SERDES1G_SER_CFG_SER_ENALI(0) |
         VTSS_F_HSIO_SERDES1G_ANA_CFG_SERDES1G_SER_CFG_SER_ALISEL(0),
         VTSS_M_HSIO_SERDES1G_ANA_CFG_SERDES1G_SER_CFG_SER_EN_WIN |
         VTSS_M_HSIO_SERDES1G_ANA_CFG_SERDES1G_SER_CFG_SER_ENALI |
         VTSS_M_HSIO_SERDES1G_ANA_CFG_SERDES1G_SER_CFG_SER_ALISEL);

  vtss_sd1g65_mcb_transfer (addr);

  return status;
}

